# .github/workflows/release-schemas.yml
name: Release Schemas

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags that look like semantic versions, e.g., v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create the release and upload assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This step now writes the tag to the GITHUB_ENV file
      - name: Get tag name
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The tag_name and other properties now reference the environment variable
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          body: |
            Schema release for version ${{ env.TAG }}
          draft: false
          prerelease: false

      - name: Upload schema assets
        run: |
          # Loop through all files in the 'schemas' directory ending with .schema.json
          for file in schemas/*.schema.json; do
            # Check if the file exists to avoid errors
            if [ -f "$file" ]; then
              # Upload the file to the release using the GitHub CLI
              gh release upload ${{ env.TAG }} "$file" --clobber
            fi
          done
        env:
          # The GitHub CLI needs an authenticated token
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
